<?php
// $Id$

/**
 * @file
 * Drupal Module: Piwik Reports
 * Sponsored by IO1, http://www.io1.biz
 * All code is released under the GNU General Public License.
 */

/**
 * Implementation of hook_menu().
 */
function piwik_reports_menu() {
  // Reports
  $items['admin/reports/piwik_reports'] = array(
    'title' => 'Piwik reports',
    'page callback' => 'piwik_reports_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'piwik_reports.pages.inc',
    'description' => 'Reports on your website visitors, your popular pages, the search engines keywords they used... and so much more.',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/piwik_reports/visitors'] = array(
    'title' => 'Visitors',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_overview'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/piwik_reports/visitors/overview'] = array(
    'title' => 'Overview',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_overview'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 1,
    'type' => MENU_DEFAULT_LOCAL_TASK
  );
  $items['admin/reports/piwik_reports/visitors/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_settings'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/reports/piwik_reports/visitors/times'] = array(
    'title' => 'Times',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_times'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/reports/piwik_reports/visitors/locations'] = array(
    'title' => 'Locations provider',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_locations'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 4,
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/reports/piwik_reports/actions'] = array(
    'title' => 'Actions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_pages'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 2,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/piwik_reports/actions/pages'] = array(
    'title' => 'Pages',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_pages'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 1,
    'type' => MENU_DEFAULT_LOCAL_TASK
  );
  $items['admin/reports/piwik_reports/actions/outlinks'] = array(
    'title' => 'Outlinks',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_outlinks'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/reports/piwik_reports/actions/downloads'] = array(
    'title' => 'Downloads',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_downloads'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/reports/piwik_reports/referers'] = array(
    'title' => 'Referers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_evolution'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 3,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/piwik_reports/referers/evolution'] = array(
    'title' => 'Evolution',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_evolution'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 1,
    'type' => MENU_DEFAULT_LOCAL_TASK
  );
  $items['admin/reports/piwik_reports/referers/search'] = array(
    'title' => 'Search engines & keywords',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_search'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/reports/piwik_reports/referers/websites'] = array(
    'title' => 'Websites',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_websites'),
    'access arguments' => array('access site reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK
  );

  return $items;
}

/**
 * Implementation of hook_theme()
 */
function piwik_reports_theme() {
  return array(
    'visitors_overview' => array(
      'template' => 'visitors-overview',
      'arguments' => array(
        'url' => NULL,
        'period' => NULL,
      ),
    ),
    'visitors_settings' => array(
      'template' => 'visitors-settings',
      'arguments' => array(
        'url1' => NULL,
        'url2' => NULL,
        'url3' => NULL,
        'url4' => NULL,
      ),
    ),
    'visitors_times' => array(
      'template' => 'visitors-times',
      'arguments' => array(
        'url' => NULL,
      ),
    ),
    'visitors_locations' => array(
      'template' => 'visitors-locations',
      'arguments' => array(
        'url' => NULL,
      ),
    ),
    'referers_evolution' => array(
      'template' => 'referers-evolution',
      'arguments' => array(
        'url' => NULL,
      ),
    ),
    'referers_search' => array(
      'template' => 'referers-search',
      'arguments' => array(
        'url' => NULL,
      ),
    ),
  );
}
